# Generated by Django 6.0.4 on 2026-04-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payments",
            options={"ordering": ["-date"], "verbose_name": "Платёж", "verbose_name_plural": "Платежи"},
        ),
        migrations.RenameField(
            model_name="payments",
            old_name="payment_amount",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="payments",
            old_name="paid_course",
            new_name="course",
        ),
        migrations.RenameField(
            model_name="payments",
            old_name="payment_date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="payments",
            old_name="paid_lesson",
            new_name="lesson",
        ),
        migrations.RenameField(
            model_name="payments",
            old_name="payment_method",
            new_name="method",
        ),
    ]
