# Generated by Django 6.0.4 on 2026-05-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_subscriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="session",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="subscriptions",
            name="subscription",
            field=models.BooleanField(default=False, verbose_name="Признак подписки"),
        ),
    ]
