# Generated by Django 6.0.4 on 2026-05-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payments_session_alter_subscriptions_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Сумма оплаты"),
        ),
    ]
