# Generated by Django 6.0.4 on 2026-04-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Название Урока")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
                ("picture", models.ImageField(blank=True, null=True, upload_to="picture/", verbose_name="Превью")),
                (
                    "link_to_video",
                    models.URLField(blank=True, max_length=500, null=True, verbose_name="Ссылка на видео"),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "db_table": "lessons",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Название курса")),
                ("picture", models.ImageField(blank=True, null=True, upload_to="picture/", verbose_name="Превью")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
                (
                    "lesson",
                    models.ManyToManyField(related_name="lessons", to="materials.lesson", verbose_name="Уроки"),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "db_table": "courses",
                "ordering": ["title"],
            },
        ),
    ]
