# Generated by Django 6.0.4 on 2026-04-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="lesson",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="lessons", to="materials.lesson", verbose_name="Уроки"
            ),
        ),
    ]
