# Generated by Django 6.0.4 on 2026-04-30 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_course_author_lesson_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="link_to_video",
            new_name="video",
        ),
    ]
