# Generated by Django 6.0.4 on 2026-05-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_rename_link_to_video_lesson_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Стоимость в рублях"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Стоимость в рублях"),
        ),
    ]
