# Generated by Django 6.0.4 on 2026-05-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_course_price_lesson_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
