# Generated by Django 6.0.4 on 2026-05-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_course_update_at_lesson_update_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="lesson",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="materials.lesson", verbose_name="Уроки"
            ),
        ),
    ]
